### PR TITLE
East-const in adoc generation

### PR DESCRIPTION
**Pull request by fpelliccioni**

### CODE REVIEW

**Comment by sdkrystian** [comment]
Please rebase onto develop first. The html generator is quite out of date, so I'm not sure if it's worth applying these changes to it

**Comment by fpelliccioni** [comment]
> Please rebase onto develop first. The html generator is quite out of date, so I'm not sure if it's worth applying these changes to it

Oops, I've just rebased – thanks for the heads up!

@vinniefalco asked me to make changes to both the adoc and html generators. Given your comment about the HTML generator being quite out of date, I'm open to suggestions. If you think it's best, we can hold off on this PR until the HTML generator is updated, or proceed if you believe the changes are still valuable in the current context. Please let me know how you'd like to proceed.

**Comment by alandefreitas** [comment]
Just do the asciidoc templates and we'll do the HTML templates later when we're copy/pasting from asciidoc. Otherwise this will be blocked forever.

**Comment by vinniefalco** [comment]
Yeah that's fair, do adoc separately.

**Comment by fpelliccioni** [comment]
I reverted the changes on HTML generation

**Pull request merged**
