### PR TITLE
support @throw/@throws/@exception

### PR DESCRIPTION
**Pull request by sdkrystian**

### CODE REVIEW

**Comment by alandefreitas** [comment]
Since we're here, it would be good to support @return already. It's a simple one.

**Comment by sdkrystian** [comment]
@alandefreitas I thought we do?

**Comment by alandefreitas** [comment]
> I thought we do?

I put something there but it's just a placeholder using the return type. It doesn't get anything from the javadoc.

**Comment by alandefreitas** [comment]
> It doesn't get anything from the javadoc.

At least last time I tried.

**Pull request merged**
