### PR TITLE
fix: missing template parameters in asciidoc templates

### PR DESCRIPTION
**Pull request by fpelliccioni**
Fixes https://github.com/cppalliance/mrdocs/issues/674

### CODE REVIEW

**Review by alandefreitas — COMMENTED** [review]
Looks good. Did you check the output?

**Comment by fpelliccioni** [comment]
> Looks good. Did you check the output?

Yes, using the example given by Andrzej

**Comment by alandefreitas** [comment]
Oh... Great. I think we can merge this as soon as this CI issue is solved.

I think Krystian broke CI in one of his last 3 commits (some USR changed) and now there's a brand need error with the `crypto` package.

**Comment by alandefreitas** [comment]
The problem CI has been fixed. Could you rebase this?

**Pull request merged**
